/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { BaseJumpRateModelV2Contract } from "./BaseJumpRateModelV2";
import { Erc20Contract } from "./Erc20";
import { Ierc20Contract } from "./Ierc20";
import { InterestRateModelContract } from "./InterestRateModel";
import { IUniswapV2FactoryContract } from "./IUniswapV2Factory";
import { IUniswapV2PairContract } from "./IUniswapV2Pair";
import { IUniswapV2Router01Contract } from "./IUniswapV2Router01";
import { IUniswapV2Router02Contract } from "./IUniswapV2Router02";
import { IwethContract } from "./Iweth";
import { JumpRateModelV2Contract } from "./JumpRateModelV2";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";
import { TesterTokenContract } from "./TesterToken";
import { TesterUniswapFactoryContract } from "./TesterUniswapFactory";
import { TesterUniswapV2Erc20Contract } from "./TesterUniswapV2Erc20";
import { TesterUniswapV2PairContract } from "./TesterUniswapV2Pair";
import { UniswapLpOracleFactoryContract } from "./UniswapLpOracleFactory";
import { UniswapLpOracleFactoryIContract } from "./UniswapLpOracleFactoryI";
import { UniswapLpOracleInstanceContract } from "./UniswapLpOracleInstance";
import { UniswapOracleFactoryContract } from "./UniswapOracleFactory";
import { UniswapOracleFactoryIContract } from "./UniswapOracleFactoryI";
import { UniswapOracleInstanceContract } from "./UniswapOracleInstance";
import { UniswapV2FactoryContract } from "./UniswapV2Factory";
import { UniswapV2PairContract } from "./UniswapV2Pair";
import { UniswapV2Router02Contract } from "./UniswapV2Router02";
import { WarpControlContract } from "./WarpControl";
import { WarpControlIContract } from "./WarpControlI";
import { WarpVaultContract } from "./WarpVault";
import { WarpVaultLpContract } from "./WarpVaultLp";
import { WarpVaultLpFactoryContract } from "./WarpVaultLpFactory";
import { WarpVaultLpFactoryIContract } from "./WarpVaultLpFactoryI";
import { WarpVaultLpiContract } from "./WarpVaultLpi";
import { WarpVaultScContract } from "./WarpVaultSc";
import { WarpVaultScFactoryContract } from "./WarpVaultScFactory";
import { WarpVaultScFactoryIContract } from "./WarpVaultScFactoryI";
import { WarpVaultSciContract } from "./WarpVaultSci";
import { WarpWrapperTokenContract } from "./WarpWrapperToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "BaseJumpRateModelV2"): BaseJumpRateModelV2Contract;
      require(name: "ERC20"): Erc20Contract;
      require(name: "IERC20"): Ierc20Contract;
      require(name: "InterestRateModel"): InterestRateModelContract;
      require(name: "IUniswapV2Factory"): IUniswapV2FactoryContract;
      require(name: "IUniswapV2Pair"): IUniswapV2PairContract;
      require(name: "IUniswapV2Router01"): IUniswapV2Router01Contract;
      require(name: "IUniswapV2Router02"): IUniswapV2Router02Contract;
      require(name: "IWETH"): IwethContract;
      require(name: "JumpRateModelV2"): JumpRateModelV2Contract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "TesterToken"): TesterTokenContract;
      require(name: "TesterUniswapFactory"): TesterUniswapFactoryContract;
      require(name: "TesterUniswapV2ERC20"): TesterUniswapV2Erc20Contract;
      require(name: "TesterUniswapV2Pair"): TesterUniswapV2PairContract;
      require(name: "UniswapLPOracleFactory"): UniswapLpOracleFactoryContract;
      require(name: "UniswapLPOracleFactoryI"): UniswapLpOracleFactoryIContract;
      require(name: "UniswapLPOracleInstance"): UniswapLpOracleInstanceContract;
      require(name: "UniswapOracleFactory"): UniswapOracleFactoryContract;
      require(name: "UniswapOracleFactoryI"): UniswapOracleFactoryIContract;
      require(name: "UniswapOracleInstance"): UniswapOracleInstanceContract;
      require(name: "UniswapV2Factory"): UniswapV2FactoryContract;
      require(name: "UniswapV2Pair"): UniswapV2PairContract;
      require(name: "UniswapV2Router02"): UniswapV2Router02Contract;
      require(name: "WarpControl"): WarpControlContract;
      require(name: "WarpControlI"): WarpControlIContract;
      require(name: "WarpVault"): WarpVaultContract;
      require(name: "WarpVaultLP"): WarpVaultLpContract;
      require(name: "WarpVaultLPFactory"): WarpVaultLpFactoryContract;
      require(name: "WarpVaultLPFactoryI"): WarpVaultLpFactoryIContract;
      require(name: "WarpVaultLPI"): WarpVaultLpiContract;
      require(name: "WarpVaultSC"): WarpVaultScContract;
      require(name: "WarpVaultSCFactory"): WarpVaultScFactoryContract;
      require(name: "WarpVaultSCFactoryI"): WarpVaultScFactoryIContract;
      require(name: "WarpVaultSCI"): WarpVaultSciContract;
      require(name: "WarpWrapperToken"): WarpWrapperTokenContract;
    }
  }
}

export {
  BaseJumpRateModelV2Contract,
  BaseJumpRateModelV2Instance
} from "./BaseJumpRateModelV2";
export { Erc20Contract, Erc20Instance } from "./Erc20";
export { Ierc20Contract, Ierc20Instance } from "./Ierc20";
export {
  InterestRateModelContract,
  InterestRateModelInstance
} from "./InterestRateModel";
export {
  IUniswapV2FactoryContract,
  IUniswapV2FactoryInstance
} from "./IUniswapV2Factory";
export {
  IUniswapV2PairContract,
  IUniswapV2PairInstance
} from "./IUniswapV2Pair";
export {
  IUniswapV2Router01Contract,
  IUniswapV2Router01Instance
} from "./IUniswapV2Router01";
export {
  IUniswapV2Router02Contract,
  IUniswapV2Router02Instance
} from "./IUniswapV2Router02";
export { IwethContract, IwethInstance } from "./Iweth";
export {
  JumpRateModelV2Contract,
  JumpRateModelV2Instance
} from "./JumpRateModelV2";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { TesterTokenContract, TesterTokenInstance } from "./TesterToken";
export {
  TesterUniswapFactoryContract,
  TesterUniswapFactoryInstance
} from "./TesterUniswapFactory";
export {
  TesterUniswapV2Erc20Contract,
  TesterUniswapV2Erc20Instance
} from "./TesterUniswapV2Erc20";
export {
  TesterUniswapV2PairContract,
  TesterUniswapV2PairInstance
} from "./TesterUniswapV2Pair";
export {
  UniswapLpOracleFactoryContract,
  UniswapLpOracleFactoryInstance
} from "./UniswapLpOracleFactory";
export {
  UniswapLpOracleFactoryIContract,
  UniswapLpOracleFactoryIInstance
} from "./UniswapLpOracleFactoryI";
export {
  UniswapLpOracleInstanceContract,
  UniswapLpOracleInstanceInstance
} from "./UniswapLpOracleInstance";
export {
  UniswapOracleFactoryContract,
  UniswapOracleFactoryInstance
} from "./UniswapOracleFactory";
export {
  UniswapOracleFactoryIContract,
  UniswapOracleFactoryIInstance
} from "./UniswapOracleFactoryI";
export {
  UniswapOracleInstanceContract,
  UniswapOracleInstanceInstance
} from "./UniswapOracleInstance";
export {
  UniswapV2FactoryContract,
  UniswapV2FactoryInstance
} from "./UniswapV2Factory";
export { UniswapV2PairContract, UniswapV2PairInstance } from "./UniswapV2Pair";
export {
  UniswapV2Router02Contract,
  UniswapV2Router02Instance
} from "./UniswapV2Router02";
export { WarpControlContract, WarpControlInstance } from "./WarpControl";
export { WarpControlIContract, WarpControlIInstance } from "./WarpControlI";
export { WarpVaultContract, WarpVaultInstance } from "./WarpVault";
export { WarpVaultLpContract, WarpVaultLpInstance } from "./WarpVaultLp";
export {
  WarpVaultLpFactoryContract,
  WarpVaultLpFactoryInstance
} from "./WarpVaultLpFactory";
export {
  WarpVaultLpFactoryIContract,
  WarpVaultLpFactoryIInstance
} from "./WarpVaultLpFactoryI";
export { WarpVaultLpiContract, WarpVaultLpiInstance } from "./WarpVaultLpi";
export { WarpVaultScContract, WarpVaultScInstance } from "./WarpVaultSc";
export {
  WarpVaultScFactoryContract,
  WarpVaultScFactoryInstance
} from "./WarpVaultScFactory";
export {
  WarpVaultScFactoryIContract,
  WarpVaultScFactoryIInstance
} from "./WarpVaultScFactoryI";
export { WarpVaultSciContract, WarpVaultSciInstance } from "./WarpVaultSci";
export {
  WarpWrapperTokenContract,
  WarpWrapperTokenInstance
} from "./WarpWrapperToken";
