/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface InterestRateModelContract
  extends Truffle.Contract<InterestRateModelInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<InterestRateModelInstance>;
}

type AllEvents = never;

export interface InterestRateModelInstance extends Truffle.ContractInstance {
  isInterestRateModel(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  /**
   * Calculates the current borrow interest rate per block
   * @param borrows The total amount of borrows the market has outstanding
   * @param cash The total amount of cash the market has
   * @param reserves The total amount of reserves the market has
   */
  getBorrowRate(
    cash: number | BN | string,
    borrows: number | BN | string,
    reserves: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  /**
   * Calculates the current supply interest rate per block
   * @param borrows The total amount of borrows the market has outstanding
   * @param cash The total amount of cash the market has
   * @param reserveFactorMantissa The current reserve factor the market has
   * @param reserves The total amount of reserves the market has
   */
  getSupplyRate(
    cash: number | BN | string,
    borrows: number | BN | string,
    reserves: number | BN | string,
    reserveFactorMantissa: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    isInterestRateModel(
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    /**
     * Calculates the current borrow interest rate per block
     * @param borrows The total amount of borrows the market has outstanding
     * @param cash The total amount of cash the market has
     * @param reserves The total amount of reserves the market has
     */
    getBorrowRate(
      cash: number | BN | string,
      borrows: number | BN | string,
      reserves: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    /**
     * Calculates the current supply interest rate per block
     * @param borrows The total amount of borrows the market has outstanding
     * @param cash The total amount of cash the market has
     * @param reserveFactorMantissa The current reserve factor the market has
     * @param reserves The total amount of reserves the market has
     */
    getSupplyRate(
      cash: number | BN | string,
      borrows: number | BN | string,
      reserves: number | BN | string,
      reserveFactorMantissa: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
