/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface WarpVaultLpFactoryContract
  extends Truffle.Contract<WarpVaultLpFactoryInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<WarpVaultLpFactoryInstance>;
}

type AllEvents = never;

export interface WarpVaultLpFactoryInstance extends Truffle.ContractInstance {
  /**
   * createWarpVaultLP allows the contract owner to create a new WarpVaultLP contract for a specific LP token
   * @param _lp is the address for the LP token this Warp Vault will manage
   * @param _lpName is the name of the LP token (ex:wETH-wBTC)*
   * @param _timelock is a variable representing the number of seconds the timeWizard will prevent withdraws and borrows from a contracts(one week is 605800 seconds)
   */
  createWarpVaultLP: {
    (
      _timelock: number | BN | string,
      _lp: string,
      _lpName: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _timelock: number | BN | string,
      _lp: string,
      _lpName: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    sendTransaction(
      _timelock: number | BN | string,
      _lp: string,
      _lpName: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _timelock: number | BN | string,
      _lp: string,
      _lpName: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    /**
     * createWarpVaultLP allows the contract owner to create a new WarpVaultLP contract for a specific LP token
     * @param _lp is the address for the LP token this Warp Vault will manage
     * @param _lpName is the name of the LP token (ex:wETH-wBTC)*
     * @param _timelock is a variable representing the number of seconds the timeWizard will prevent withdraws and borrows from a contracts(one week is 605800 seconds)
     */
    createWarpVaultLP: {
      (
        _timelock: number | BN | string,
        _lp: string,
        _lpName: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _timelock: number | BN | string,
        _lp: string,
        _lpName: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      sendTransaction(
        _timelock: number | BN | string,
        _lp: string,
        _lpName: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _timelock: number | BN | string,
        _lp: string,
        _lpName: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
